#!/usr/bin/env python3
"""Guide to find permissions tab"""

print("="*80)
print("HOW TO GRANT PERMISSIONS ON CLOUD RUN JOB")
print("="*80)

print("\nYou're currently on the Job Details page.")
print("The PERMISSIONS tab might be in a different location.")
print()

print("OPTION 1: Check if PERMISSIONS tab exists")
print("-" * 80)
print("Look at the tabs at the top of the job details page.")
print("You should see: History | Observability | Triggers | YAML")
print("If there's a 'PERMISSIONS' or 'IAM' tab, click it.")
print()

print("OPTION 2: Use the IAM & Admin page")
print("-" * 80)
print("1. Go to: https://console.cloud.google.com/iam-admin/iam?project=boxwood-chassis-332307")
print("2. In the filter/search box, type: inventory-updater")
print("3. Or look for resources and find the Cloud Run Job")
print()

print("OPTION 3: Use gcloud CLI (if you have it)")
print("-" * 80)
print("Run this command:")
print()
print(f'gcloud run jobs add-iam-policy-binding inventory-updater \\')
print(f'  --region=us-east1 \\')
print(f'  --member="serviceAccount:scheduler-invoker@boxwood-chassis-332307.iam.gserviceaccount.com" \\')
print(f'  --role="roles/run.invoker"')
print()

print("OPTION 4: Check the job's YAML")
print("-" * 80)
print("1. Click the 'YAML' tab on the job details page")
print("2. Look for 'iamPolicy' or 'serviceAccount' sections")
print("3. But permissions are usually set via IAM, not in YAML")
print()

print("="*80)
print("MOST LIKELY LOCATION:")
print("="*80)
print("\nIn Cloud Run Jobs, permissions are usually set via:")
print("1. The IAM & Admin page (project-level, but can filter by resource)")
print("2. Or there might be a 'PERMISSIONS' button/icon near the top")
print("   (Look for a shield icon or 'PERMISSIONS' button)")
print()
print("Try clicking around the job details page - there might be")
print("a 'PERMISSIONS' button or 'SHOW INFO PANEL' that reveals it.")
print("="*80)
